Update README.md
Beardless-sheik/Alicks-Portfolio pull request #6
Opened 2021-06-21 10:44 UTC by Beardless-sheik

-Added live project link in README

2021-06-21 10:59 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @Beardless-sheik     ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- Your README and PR message are descriptive ✔️ 
- Your project runs as expected and is responsive as well. ✔️ 

 However, there are changes required for you to make in order for this project to be approved. 

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. :smile:

- - -

### **Recommended** ♻️
_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**Note that you still have 2 more reviews as written in the [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561), however, if you feel this review is unfair, you can request a second opinion using [this](https://airtable.com/shrQAqnBwek5a0O0s) form.**

__Kindly make the necessary changes and submit another code review request.__

2021-06-21 10:59 UTC, Temmarie commented on README.md
>  ## Authors
- [ ] Good job here! Your readme is very descriptive but it needs a few tweaks and you're good to go!
- A good README should have a description that is clear, short, and to the point. It should describe the importance of your project, what it does and how to use it. This way technical and non-technical users can understand how to use it.
- Include acknowledgements to Figma for the design template.
- The `Getting Started` section which includes information on how to run the project locally needs to be updated and include the necessary steps to clone it, noting that there might be non-technical users as well.
- Check out how to use [markdowns](https://www.markdownguide.org/cheat-sheet/) for hyperlinks in the readme.
- Also, you have a horizontal overflow in your project on Desktop screens, kindly fix it.

2021-06-21 14:02 UTC, ahcodes approved these changes

2021-06-22 10:47 UTC, Temmarie approved these changes
## Status: Approved ✔️ 
### Hi @Beardless-sheik  , 
#### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  Congratulations! 🎉 


_**Note that when giving comments or raising issues, it should be done on the issues tab. Approving the project before it is approved by the TSE confuses the next code reviewer.**_
#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2021-06-22 10:56 UTC, merged